import{a as q,S as v,i as E}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const x="https://pixabay.com/api/",M="51706483-b1178684cf0cda85acd7b38c0";async function B(t,o=1){const r={key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o},{data:i}=await q.get(x,{params:r});return i}const d=document.querySelector(".gallery");document.querySelector(".loader");const g=document.querySelector(".load-more");let c=null;function P(t,o=!1){if(!t.length)return;const r=t.map(({webformatURL:i,largeImageURL:e,tags:s,likes:a,views:b,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img class="gallery-image" src="${i}" alt="${s}" loading="lazy" />
        </a>
        <ul class="stats">
          <li class="stats-item"><b>Likes:</b> ${a}</li>
          <li class="stats-item"><b>Views:</b> ${b}</li>
          <li class="stats-item"><b>Comments:</b> ${w}</li>
          <li class="stats-item"><b>Downloads:</b> ${S}</li>
        </ul>
      </li>
    `).join("");if(d.insertAdjacentHTML("beforeend",r),c?c.refresh():c=new v(".gallery a",{captionsData:"alt",captionDelay:250}),!o){const{height:i}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}function $(){d.innerHTML=""}function A(){g.classList.remove("is-hidden")}function h(){g.classList.add("is-hidden")}const p=document.querySelector(".form"),C=p.elements["search-text"],I=document.querySelector(".load-more"),y=document.querySelector(".loader"),n=document.createElement("p");n.classList.add("end-message","is-hidden");n.style.textAlign="center";n.style.marginTop="15px";n.style.fontSize="16px";document.querySelector(".controls").appendChild(n);let u="",l=1,f=0;const O=15;p.addEventListener("submit",_);I.addEventListener("click",H);async function _(t){if(t.preventDefault(),u=C.value.trim(),l=1,f=0,!u){m("warning","Please enter a search query!");return}$(),h(),n.classList.add("is-hidden"),await L()}async function H(){l+=1,h(),n.classList.add("is-hidden"),await L(!0)}async function L(t=!1){y.classList.remove("is-hidden");try{const o=await B(u,l);if(f=o.totalHits,o.hits.length===0&&!t){m("info","Sorry, no images found.");return}P(o.hits,!t);const r=l*O;r<f?A():(h(),r>0&&(n.textContent="We're sorry, but you've reached the end of search results.",n.classList.remove("is-hidden")))}catch(o){m("error","Something went wrong."),console.error(o)}finally{y.classList.add("is-hidden")}}function m(t,o){const r={title:t==="error"?"Error":t==="warning"?"Warning":t==="info"?"Info":"",message:o,position:"topRight"};E[t](r)}
//# sourceMappingURL=index.js.map
